# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebaseid', models.CharField(blank=True, default='', max_length=300)),
                ('week_num', models.IntegerField()),
                ('year', models.IntegerField()),
                ('mon_start', models.CharField(blank=True, default='', max_length=20)),
                ('mon_end', models.CharField(blank=True, default='', max_length=20)),
                ('tues_start', models.CharField(blank=True, default='', max_length=20)),
                ('tues_end', models.CharField(blank=True, default='', max_length=20)),
                ('wed_start', models.CharField(blank=True, default='', max_length=20)),
                ('wed_end', models.CharField(blank=True, default='', max_length=20)),
                ('thurs_start', models.CharField(blank=True, default='', max_length=20)),
                ('thurs_end', models.CharField(blank=True, default='', max_length=20)),
                ('fri_start', models.CharField(blank=True, default='', max_length=20)),
                ('fri_end', models.CharField(blank=True, default='', max_length=20)),
                ('sat_start', models.CharField(blank=True, default='', max_length=20)),
                ('sat_end', models.CharField(blank=True, default='', max_length=20)),
                ('sun_start', models.CharField(blank=True, default='', max_length=20)),
                ('sun_end', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='firebaseid',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
