# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_announcements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='designee',
        ),
    ]
