# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_announcements_designee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('firebaseid', models.CharField(blank=True, default='', max_length=300)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
