# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20170314_0122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_Table_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='task_table',
            name='task_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_list', to='task.Task_Table_List'),
        ),
    ]
