# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20170320_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_table',
            name='created_timestamp',
            field=models.FloatField(default=1490100827.325077, null=True),
        ),
    ]
