# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_table_created_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_table',
            name='created_timestamp',
            field=models.IntegerField(default=123, editable=False),
        ),
    ]
