# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20170321_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_table',
            name='created_timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
