# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20170321_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_table',
            name='completed_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task_table',
            name='last_modified_timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
