# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20170321_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_table',
            name='completed_time',
        ),
        migrations.AlterField(
            model_name='task_table',
            name='created_timestamp',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task_table',
            name='last_modified_timestamp',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
