# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_auto_20170321_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_table',
            name='deadline',
            field=models.IntegerField(default=60, null=True),
        ),
    ]
