# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_task_table_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='task_table',
            name='last_modified_timestamp',
        ),
    ]
